### ISSUE TITLE
Grammatical error in description of section: "Google cloud shell"

### ISSUE THREAD

**Issue by adi-dhulipala** [googlecodelabs/nyc-subway-station-locator#3]
In the [code-lab description](https://codelabs.developers.google.com/codelabs/nyc-subway-station-locator/index.html?index=..%2F..%2Findex#1) the "Google Cloud Shell" section reads:

> #### Google Cloud Shell
> .... 
> an automatically provisioned Linux virtual machine is loaded with all the development tools
> ...

whereas it should actually read:

> #### Google Cloud Shell
> .... 
> an automatically provisioned Linux virtual machine **_which_** is loaded with all the development tools
> ...

**Comment by domesticmouse** [comment]
Thanks for the heads up. The updated codelab should be live in the next twenty minutes or so.
